# Generated by Django 3.0.7 on 2020-07-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20200710_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='title',
            field=models.CharField(default='Balance', max_length=10),
        ),
    ]
